config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :runners do
    resources :runs
  end

  resources :runs
  resources :events
  resources :runner_events

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/leaderboard' => 'events#leaderboard'

  get '/auth/github/callback' => 'sessions#create'
end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :runs
  has_many :runner_events
  has_many :events, through: :runner_events

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(:username => auth_hash[:info][:nickname]).first_or_create do |runner|
      runner.password = SecureRandom.hex
    end
  end

end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :check_privileges, except: [:new, :create]

  def new
    @runner = Runner.new
  end

  def create
    @runner = Runner.new(runner_params)
    if @runner.valid?
      @runner.save
      session[:runner_id] = @runner[:id]
      redirect_to runner_path(@runner.id)
    else
      render :new
    end
  end

  def show
    @runner = Runner.find_by(id: params[:id])
    if current_runner.id != @runner.id
      redirect_to "/", notice: "You don't have permission to be here"
    end
  end

  private

    def runner_params
      params.require(:runner).permit(:username, :password)
    end

end

app/views/runners/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if @runner.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@runner.errors.count, "error") %>
      prohibited this runner from being saved:
    </h2>

    <ul>
    <% @runner.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="feature">
  <%= form_for @runner, controller: 'runners', action: 'create' do |f| %>
    <h1>Sign Up</h1>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br />
    <%= f.label :password %>
    <%= f.text_field :password %>
    <br />
    <%= f.submit "Create Runner" %>
  <% end %>

  <%= link_to('Login with GitHub', '/auth/github') %>
</div>

app/views/runners/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="feature">
  <h1 class="headline">Welcome, <%= @runner.username %>!</h1>
  <h2><%= current_event_description %></h2>

  <h3><%= link_to "Choose an event to train for", new_runner_event_path %></h3>
</div>

<div class="runner_show">
  <h3 class="headline"><%= current_runner.username %>'s training runs</h3>
  <h4>Just back from a run? Log the details <%= link_to "here!", new_runner_run_path(@runner) %></h4>
  <p><%= current_runner.username %>, you've gone for <%= @runner.runs.count %> runs!</p>
  <p>Check them out <%= link_to "here", runner_runs_path(@runner.id) %></p>
</div>

<div class="runner_show">
  <h3 class="headline"><%= current_runner.username %>'s events</h3>
  <h4>Follow this link to check out all the events! <%= link_to "Events", events_path %></h4>
  <p><%= @runner.username %>, you have <%= @runner.runner_events.count %> events.
  <p>Check out your events <%= link_to "here", runner_events_path %></p>
</div>

<div>
  <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>
</div>