config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :runners do
    resources :runs
  end

  resources :runs
  resources :events
  resources :runner_events

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/leaderboard' => 'events#leaderboard'

  get '/auth/github/callback' => 'sessions#create'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :runner_events
  has_many :runners, through: :runner_events

  validates :description, presence: true

  def new
  end

  def self.accomplished
    scope :completed, -> { where(completed: true) }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_privileges

  def index
    @sorted_events = Event.all
    # @sorted_events = events.sort { |eventA, eventB| eventA.description <=> eventB.description }

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @sorted_events }
    end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find_by(id: params[:id])
    @finishers = completed_by(@event.runners)

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @finishers }
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.valid?
      @event.save
      redirect_to new_runner_event_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update

    @event = Event.find_by(id: params[:id])
    @event.update(event_params)
    if @goal.save
      redirect_to @goal
    else
      render :edit
    end
  end

  def leaderboard
    @events = Event.all

  end

  private

    def event_params
      params.require(:event).permit(:description)
    end

    def completed_by(runners)
      finished_events = []
      runners.each do |runner|
        runner.runner_events.each do |r_e|
          if r_e.completed != nil && r_e.event_id == @event.id
            finished_events << r_e
          end
        end
      end
      finished_events
    end

end

app/views/events/index.html.erb
<h1>Events via JavaScript</h1>

<div id="eventDiv">
  <% @sorted_events.each do |event| %>
    <div id="event-<%= event.id %>">
      <h3 id="event-<%= event.id %>-description"></h3>
      <p id="event-<%= event.id %>-link"></p>
    </div>
  <% end %>
</div>

<button id="getEvents">Get Events Via JavaScript</button>

<h3><%= link_to "Home", runner_path(current_runner.id) %></h3>

<button id="sortEvents">Sort Events</button>

<script type="text/javascript" charset="utf-8">

  $(function() {
    $("#sortEvents").on("click", function(){
      $.get("/events.json", function(data){
        $("#eventDiv").html("")

        let sortedRuns = data.sort(function(a, b) {
          let eventA = a.description.toUpperCase(); // ignore upper and lowercase
          let eventB = b.description.toUpperCase(); // ignore upper and lowercase
          if (eventA < eventB) {
            return -1;
          }
          if (eventA > eventB) {
            return 1;
          }

          // names must be equal
          return 0;
        });

        sortedRuns.forEach(run => $("#eventDiv").append(`
            <div id="event-${run.id}">
            <h3 id="event-${run.id}-description">${run.description}</h3>
            <p id="event-${run.id}-link">See this run</p>
          </div>`))

      })
    })
  })


</script>

app/views/events/leaderboard.html.erb
<% @events.each do |e| %>
  <p><%= e.description %></p>
  <p><%= e.runner_events.accomplished.quickest.runner.username %></p>
  <p><%= e.runner_events.accomplished.quickest.finish_time %> minutes</p>
<% end %>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved:
    </h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="feature">
  <h1>New Event Page</h1>

  <h3>In the future, it would be great if this app could scrape real events from the web.</h3>

  <%= form_for @event do |f| %>
    <h3><%= f.label "Create a new event" %></h3>
    <%= f.text_field :description %>
    <br />
    <%= f.submit %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="feature">

  <h1>Event:</h1>
  <h2><%= @event.description %></h2>

  <button class="getFinishers" data-id="<%= @event.id %>">Get finishers</button>

  <% @finishers.each do |finisher| %>
    <div id="finisher-<%= finisher.id %>">
      <p id="finisher-<%= finisher.id %>-username"></p>
      <p id="finisher-<%= finisher.id %>-finish_time"></p>
    </div>
  <% end %>

  <h3><%= link_to "Home", runner_path(current_runner.id) %></h3>

</div>

<script type="text/javascript" charset="utf-8">

  $(".getFinishers").on("click", function() {
    const id = parseInt(this.dataset["id"]);
    $.get("/events/" + id + ".json", function(finishers) {
      for(let i = 0; i < finishers.length; i++) {
        const finisher_id = finishers[i]["id"];
        $("#finisher-" + finisher_id).addClass("highlight");
        $("#finisher-" + finisher_id + "-username").text(`Completed by: ${finishers[i]["runner"].username}`)
        $("#finisher-" + finisher_id + "-finish_time").text(`Finish Time: ${finishers[i].finish_time} minutes`)
        $(".getFinishers").hide();
      }
    })
  })

</script>