config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :runners do
    resources :runs
  end

  resources :runs
  resources :events
  resources :runner_events

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/leaderboard' => 'events#leaderboard'

  get '/auth/github/callback' => 'sessions#create'
end

app/models/runner_event.rb
class RunnerEvent < ActiveRecord::Base
  belongs_to :runner
  belongs_to :event

  validates :runner_id, presence: true
  validates :runner_id, numericality: {only_integer: true}
  validates :event_id, presence: true
  validates :event_id, numericality: {only_integer: true}

  def self.quickest
    self.order(finish_time: :asc).first
  end

  scope :accomplished, -> { where(completed: true) }

end

app/controllers/runner_events_controller.rb
class RunnerEventsController < ApplicationController
  before_action :check_privileges

  def new
    @runner_event = RunnerEvent.new
  end

  def index
    @events = current_runner.events
  end

  def show
    @runner_event = RunnerEvent.find_by(id: params[:id])
    if @runner_event.runner_id == current_runner.id
      @event = Event.find_by(id: @runner_event.event_id)
    else
      redirect_to "/", notice: "You don't have permission to view this event"
    end
  end

  def create
    runner_event = RunnerEvent.new(runner_event_params)
    runner_event.runner_id = current_runner.id
  

    if !current_runner.events.include?(runner_event.event) && runner_event.save
      redirect_to runner_path(current_runner.id)
    else
      redirect_to new_runner_event_path, notice: "Please enter a valid event"
    end
  end

  def edit
    @runner_event = RunnerEvent.find_by(id: params[:id])
  end

  def update
    @runner_event = RunnerEvent.find_by(id: params[:id])
    if !valid_update_params(runner_event_params)
      flash[:notice] = "Must check 'completed' and provide time in minutes"
      redirect_to edit_runner_event_path(@runner_event.id)
    else @runner_event.update(runner_event_params)
      if @runner_event.save
        redirect_to runner_event_path(@runner_event.id)
      else
        render :new
      end
    end
  end

  private

    def runner_event_params
      params.require(:runner_event).permit(:runner_id, :event_id, :completed, :finish_time)
    end

    def valid_update_params(runner_event_params)
      if runner_event_params[:completed] == "1" && !!runner_event_params[:finish_time].match(/\A\d+\z/)
        true
      else
        false
      end
    end

end

app/views/runner_events/edit.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="feature">

  <%= form_for @runner_event do |f| %>
    <h3><%= Event.find_by(id: @runner_event.event_id).description %></h3>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <br />
    <%= f.label "Finish Time (in minutes)" %>
    <%= f.text_field :finish_time %>
    <br />
    <%= f.submit "Wow that was an awesome event!"%>
  <% end %>

</div>

<h3><%= link_to "Home", runner_path(current_runner.id) %></h3>

app/views/runner_events/index.html.erb
<div class="feature">
  <h1><%= current_runner.username %>'s Events Index</h1>

  <ul>
    <% current_runner.runner_events.accomplished.each do |r_e| %>

        <div class="highlight">
          <h2>Congratulations on completing this event!</h2>
          <p><%= event_completed(r_e) %></p>
          <p>Completed in: <%= completed_time(current_runner, Event.find_by(id: r_e.event_id)) %> minutes</p>
          <p><%= link_to "Event Details", event_path(Event.find_by(id: r_e.event_id)) %></p>
        </div>

    <% end %>
  </ul>

  <% current_runner.runner_events.each do |r_e| %>
    <% if r_e.completed == nil %>
      <h2><%= event_completed(r_e)%></h2>
      <h3>Completed this event? Enter the details <%= link_to "here", edit_runner_event_path(r_e.id) %></h3>
      <p><%= link_to "Event Details", event_path(Event.find_by(id: r_e.event_id)) %></p>
    <% end %>
  <% end %>

  <h3><%= link_to "Home", runner_path(current_runner.id) %></h3>

  <br />

  <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
    <input type=submit value='logout'>
  <% end %>
</div>

app/views/runner_events/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="feature">
  <h1>Set your event here!</h1>

  <%= form_for @runner_event do |f| %>
    <%= f.label "Event selection" %>
    <br />
    <%= f.collection_select(:event_id, Event.all, :id, :description, include_blank: "Select an event") %>
    <br />
    <%= f.submit "I can do it!" %>
  <% end %>

  <h3>Don't see the event you're training for?  Add it <%= link_to "here", new_event_path %></h3>
</div>

<h3><%= link_to "Home", runner_path(current_runner.id) %></h3>

app/views/runner_events/show.html.erb
<div class="feature">
  <h1><%= current_runner.username %>'s page for <%= @event.description %></h1>
  <h3><%= event_completed(@runner_event) %></h3>
  <h3>Completed in: <%= completed_time(current_runner, @event) %> minutes</h3>

  <%= link_to "Event Details", event_path(@event.id) %>
  <br />

  <h3><%= link_to "Home", runner_path(current_runner.id) %></h3>
</div>